#!/usr/bin/env bash

set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

function run {(
  export BULETINA_PORT=8080
  export BULETINA_BASE_URL=http://127.0.0.1:8080
  export BULETINA_JWT_SECRET=some_random_string
  export BULETINA_SMTP_SERVER=mail.server.com
  export BULETINA_SMTP_USERNAME=user
  export BULETINA_SMTP_PASSWORD=pass
  export BULETINA_SMTP_SENDER=noreply@example.com
  mvn clean compile exec:java
)}

function fatjar {(
  mvn clean package
)}

function version {(
  # shellcheck disable=SC2016
  mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec
)}

function docker-publish {(
  version="$(version)_$(date +'%Y%m%d_%H%M%S')"
  cd docker
  export BULETINA_TAG="${version}"
  docker-compose build
  docker-compose push

  printf "Published version: %s\n" "${version}"
)}

function devenv {(
  docker-compose -p buletina-devenv -f ./docker/docker-compose.devenv.yml "$@"
)}

function devenv-db-login {(
  devenv exec db psql -U buletina
)}

function help {(
  echo "Available commands:"
  for fn in $(compgen -A function); do echo "  ${fn}"; done
)}

[ -z "$1" ] && help && exit 0
"$1" "${@:2}"
