version: '3.8'

services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: buletina
      POSTGRES_PASSWORD: buletina
      POSTGRES_DB: buletina
    ports:
    - 5432:5432

  smtp:
    image: gessnerfl/fake-smtp-server:1.6.1
    restart: always
    environment: 
      "server.port": 8081
      "fakesmtp.port": 5025
    ports:
      - 8081:8081
      - 5025:5025
